language: node_js
node_js: node
services:
  - mongodb
env:
  global:
    secure: leKt6wDE3WvebXKFg1JbTg1tGzyim3c8RBB63Qp+V/liZvnZb7XNWWJ/7Gu9OqswB5durrD9wZbgA/SmkHQpA4Dz1MYD6DpOYx2mpND1RxZ0w7pUbw27zuvCLe0GsiqqtAU1At0diPjK82RvhGqNBt7h2AB3OoI1r8TLru8LEd20hkNVJKpeW7ZJdoNu8e3kXUu7tAAYtRFtsifv8kwWmo5PeB9HPLuijUZv91eUdMB1droNThAufSwFfqtaSqKXpBqhcbAcdRy8gqRAIjYw1MPWeLWAZcebdlYw2WfPRp2mxkWSV2YGUR8q+vafVZsaAWzSk33hhkqUx9i2wVJihq5PGs0rUlYDy3QMNZuN5CqfQjtdRefquoSeuQKs0KM31lpxN5mUjaJb9BtqSHThAAXL6scya5E0c/WAx0Q0Vf2/gErxyx50CqTxrTuYuWJh4+cfehYifXBykFSNVY+SlvbXFyiT/FOeStikddfepPXoD1NFi5BPe7ZKjfuLvBthIAdsSCn10P+ehu9ol1MyS8G5smpTGp2WXinBVYF279Ngcye00qfZNkqlc7Uuiil+tOgV9g4utSBYv3kvxNaAyV4fbDzSeT20p7OITkYQz9yOqJsKb2pQW29PWlt8xAuE4Lx0MkY001PEGvfNhTRyeKiE8iEVXF86pTJ76rl1tbs=
